
CREATE TABLE ROOMTYPE (
  RoomTypeID INT PRIMARY KEY,
  TypeName VARCHAR2(50) NOT NULL,
  BasePrice NUMERIC(10,2) NOT NULL CHECK (BasePrice > 0),
  Description VARCHAR2(500),
  BedType VARCHAR2(50)
);


CREATE TABLE ROOMSTATUS (
  StatusID INT PRIMARY KEY,
  StatusName VARCHAR2(20) NOT NULL UNIQUE
);


CREATE TABLE ROOM (
  RoomID INT PRIMARY KEY,
  RoomNumber INT NOT NULL UNIQUE,
  Floor INT NOT NULL CHECK (Floor >= -1), 
  MaxOccupancy INT NOT NULL CHECK (MaxOccupancy > 0),
  PhoneNumber VARCHAR2(20),
  RoomTypeID INT NOT NULL,
  StatusID INT NOT NULL,
  CONSTRAINT fk_room_type FOREIGN KEY (RoomTypeID) REFERENCES ROOMTYPE(RoomTypeID),
  CONSTRAINT fk_room_status FOREIGN KEY (StatusID) REFERENCES ROOMSTATUS(StatusID)
);


CREATE TABLE AMENITY (
  AmenityID INT PRIMARY KEY,
  AmenityName VARCHAR2(50) NOT NULL,
  AmenityCategory VARCHAR2(50)
);


CREATE TABLE ROOMMAINTENANCE (
  MaintenanceID INT PRIMARY KEY,
  StartDate DATE NOT NULL,
  EndDate DATE,
  Description VARCHAR2(1000) NOT NULL,
  RepairCost NUMERIC(10,2) DEFAULT 0 CHECK (RepairCost >= 0),
  MaintenanceStatus VARCHAR2(20) NOT NULL,
  RoomID INT NOT NULL,
  CONSTRAINT fk_maint_room FOREIGN KEY (RoomID) REFERENCES ROOM(RoomID),
  CONSTRAINT chk_maint_dates CHECK (EndDate >= StartDate OR EndDate IS NULL),
  CONSTRAINT chk_maint_status CHECK (MaintenanceStatus IN ('Reported', 'In Progress', 'Fixed', 'Verified'))
);


CREATE TABLE SEASON (
  SeasonID INT PRIMARY KEY,
  SeasonName VARCHAR2(50) NOT NULL,
  StartDate DATE NOT NULL,
  EndDate DATE NOT NULL,
  CONSTRAINT chk_season_dates CHECK (EndDate > StartDate)
);


CREATE TABLE SPECIALOFFER (
  OfferID INT PRIMARY KEY,
  OfferName VARCHAR2(50) NOT NULL,
  DiscountPercentage NUMERIC(5,2) DEFAULT 0 CHECK (DiscountPercentage BETWEEN 0 AND 100)
);


CREATE TABLE PRICERATE (
  RateID INT PRIMARY KEY,
  SeasonID INT NOT NULL,
  OfferID INT,
  RoomTypeID INT NOT NULL,
  FinalPrice NUMERIC(10,2) NOT NULL CHECK (FinalPrice > 0),
  CONSTRAINT fk_pr_season FOREIGN KEY (SeasonID) REFERENCES SEASON(SeasonID),
  CONSTRAINT fk_pr_offer FOREIGN KEY (OfferID) REFERENCES SPECIALOFFER(OfferID),
  CONSTRAINT fk_pr_roomtype FOREIGN KEY (RoomTypeID) REFERENCES ROOMTYPE(RoomTypeID)
);

//
CREATE TABLE ROOMAMENITY (
  RoomID INT NOT NULL,
  AmenityID INT NOT NULL,
  PRIMARY KEY (RoomID, AmenityID),
  CONSTRAINT fk_ra_room FOREIGN KEY (RoomID) REFERENCES ROOM(RoomID),
  CONSTRAINT fk_ra_amenity FOREIGN KEY (AmenityID) REFERENCES AMENITY(AmenityID)
);